GET http://localhost:3001/api/cart

###

GET http://localhost:3001/api/cart/67edb78261f9ac0fd66fd6c2

### 

POST http://localhost:3001/api/cart HTTP/1.1
Content-Type: application/json

{
    "productId": "prod_Rzx5uYmdKhwENl",
    "quantity": 10
}

###

DELETE  http://localhost:3001/api/cart HTTP/1.1
Content-Type: application/json

{
    "productId": "prod_Rzx3KEO8kO3gT9"
}